# Generated by Django 5.2.7 on 2025-10-22 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main headline (max 100 chars for optimal SEO)",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle/tagline (max 80 chars for readability)",
                        max_length=80,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short description (max 200 chars for meta description)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated URL slug for SEO",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta title (max 60 chars, auto-filled if empty)",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description (max 160 chars, auto-filled if empty)",
                        max_length=160,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Main product image (recommended: 800x600px)",
                        upload_to="slides/images/",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility and SEO (auto-filled if empty)",
                        max_length=125,
                    ),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        blank=True,
                        help_text="WebP version (auto-generated for better performance)",
                        null=True,
                        upload_to="slides/webp/",
                    ),
                ),
                (
                    "background_gradient",
                    models.CharField(
                        default="linear-gradient(135deg, #2D5A3D 0%, #3E9A42 50%, #4CAF50 100%)",
                        help_text="CSS gradient for slide background",
                        max_length=200,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Text color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text (optional)",
                        max_length=30,
                    ),
                ),
                (
                    "cta_link",
                    models.URLField(
                        blank=True, help_text="CTA button link URL (optional)"
                    ),
                ),
                (
                    "cta_internal_link",
                    models.CharField(
                        blank=True,
                        help_text="Internal link path (e.g., /catalog/fresh-produce)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Display this slide on website"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Display order (1 = first)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this slide was viewed"
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of CTA clicks"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this slide was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification time"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When this slide was published", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start displaying from this date (optional)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stop displaying after this date (optional)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Slider",
                "verbose_name_plural": "Hero Sliders",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="mainapp_her_is_acti_21f89b_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="mainapp_her_start_d_575fe5_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="mainapp_her_created_cb86c6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SliderAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, help_text="Analytics date"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, help_text="Daily view count"
                    ),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, help_text="Daily click count"
                    ),
                ),
                (
                    "unique_visitors",
                    models.PositiveIntegerField(
                        default=0, help_text="Unique visitors count"
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="mainapp.heroslider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slider Analytics",
                "verbose_name_plural": "Slider Analytics",
                "ordering": ["-date"],
                "unique_together": {("slider", "date")},
            },
        ),
    ]
