# Generated by Django 5.2.7 on 2025-10-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroslider",
            name="background_gradient",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="text_color",
        ),
    ]
