# Generated by Django 5.2.7 on 2025-10-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_remove_design_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="slideranalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="slideranalytics",
            name="slider",
        ),
        migrations.RemoveIndex(
            model_name="heroslider",
            name="mainapp_her_start_d_575fe5_idx",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="click_count",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="cta_internal_link",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="cta_link",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="cta_text",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="heroslider",
            name="view_count",
        ),
        migrations.DeleteModel(
            name="SliderAnalytics",
        ),
    ]
